version: "3.9"
services:
  ip-checker:
    build: .
    image: ip-checker-image:latest
    container_name: ip-checker-container 
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    env_file:
      - .env