apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip-checker
  namespace: ip-checker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ip-checker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ip-checker
                port:
                  number: 80
